# Generated by Django 2.2.1 on 2020-04-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1020)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=1024)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=10000)),
                ('education', models.TextField(max_length=12033)),
                ('skills', models.TextField(verbose_name=23433)),
                ('why', models.TextField(blank=True, max_length=24443, null=True)),
                ('departments', models.TextField(max_length=32432)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
